/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chat;

import static chat.InterfaceClient.socketClient;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.InetAddress;
import java.net.Socket;
import javax.swing.JOptionPane;

/**
 * Classe Subscribe pour les inscriptions des utilisateurs dans la base de données.
 * <li>Vérifie si les champs sont tous remplis</li>
 * <li>Envoi la séquence d'inscription au serveur (le serveur vérifiela disponibilité du Pseudonyme)</li>
 * <li>Reçoie le droit, d'inscription si le pseudo est dispo, pas d'inscription si le pseudo a déjà été inscrit</li>
 * @author anamwa
 */
public class Subscribe extends javax.swing.JFrame {

    /**
     * Crée cette interface graphique
     */
    public Subscribe() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nomUser = new javax.swing.JTextField();
        prenomUser = new javax.swing.JTextField();
        passwordUser = new javax.swing.JPasswordField();
        subscribe = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        pseudo = new javax.swing.JTextField();
        bienvenue = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuFichier = new javax.swing.JMenu();
        menuEdition = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvenue sur l'interface d'inscription, veuillez remplir vos informations ");

        jLabel2.setText(" Nom :");

        jLabel3.setText("Prénom :");

        jLabel4.setText("Mot de passe :");

        nomUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomUserActionPerformed(evt);
            }
        });

        prenomUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomUserActionPerformed(evt);
            }
        });

        passwordUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordUserActionPerformed(evt);
            }
        });

        subscribe.setText("S'inscrire");
        subscribe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subscribeActionPerformed(evt);
            }
        });

        jLabel5.setText("Pseudonyme :");

        bienvenue.setText("Retour vers l'Accueil");
        bienvenue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bienvenueActionPerformed(evt);
            }
        });

        jLabel6.setText("Tous les champs sont obligatoires");

        menuFichier.setText("Fichier");
        jMenuBar1.add(menuFichier);

        menuEdition.setText("Edition");
        jMenuBar1.add(menuEdition);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(subscribe, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bienvenue))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(prenomUser, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomUser, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pseudo)
                                    .addComponent(passwordUser, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(66, 66, 66)))))
                .addGap(0, 196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nomUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(prenomUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(pseudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(passwordUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subscribe)
                    .addComponent(bienvenue))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomUserActionPerformed

    private void prenomUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenomUserActionPerformed

    private void passwordUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordUserActionPerformed
    
    // Revenir à l'accueil 
    private void bienvenueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bienvenueActionPerformed
        // TODO add your handling code here:
        new Bienvenue();
        setVisible(false);
    }//GEN-LAST:event_bienvenueActionPerformed
    
    //Procéssus d'inscription côté app client
    private void subscribeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subscribeActionPerformed
        // TODO add your handling code here:
        if (nomUser.getText().equals("") || prenomUser.getText().equals("") || pseudo.getText().equals("") || passwordUser.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Veuillez remplir tous les champs", "Erreur", JOptionPane.PLAIN_MESSAGE);
        }else{  //Former la requête SQL et l'envoyer comme un String au serveur
            String message = "INSERT INTO utilisateur (nomUtilisateur, prenomUtilisateur, emailUtilisateur, motDePasse) values ('"+ nomUser.getText() +"','"+ prenomUser.getText()+"','"+ pseudo.getText() +"','"+ passwordUser.getText() +"');";
            message = "inscription#"+message;
            try{
                socketClient = new Socket(InetAddress.getLocalHost(), 4444);
                PrintWriter donneeOut = new PrintWriter(socketClient.getOutputStream());
                donneeOut.println(message);
                donneeOut.flush();
                
                InputStreamReader streamMessage = new InputStreamReader(socketClient.getInputStream());			
                BufferedReader donneeIn = new BufferedReader(streamMessage);
                String connecter = donneeIn.readLine();
                if (connecter.compareTo("ok")==0){  //Si le droit d'inscription a été accordé
                    JOptionPane.showMessageDialog(null, "Congrats, Vous êtes bien inscrît", "Congrats", JOptionPane.PLAIN_MESSAGE);
                    nomUser.setText("");
                    prenomUser.setText("");
                    pseudo.setText("");
                    passwordUser.setText("");                
                }else{  //Si le droit a été refusé
                    JOptionPane.showMessageDialog(null, "Erreur, l'e-mail introduit existe déjà", "Erreur", JOptionPane.PLAIN_MESSAGE);
                    nomUser.setText("");
                    prenomUser.setText("");
                    pseudo.setText("");
                    passwordUser.setText("");
                }
            }catch(Exception e){
                System.out.println("Connexion au serveur impossible");
            }
        }
        
    }//GEN-LAST:event_subscribeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bienvenue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuEdition;
    private javax.swing.JMenu menuFichier;
    private javax.swing.JTextField nomUser;
    private javax.swing.JPasswordField passwordUser;
    private javax.swing.JTextField prenomUser;
    private javax.swing.JTextField pseudo;
    private javax.swing.JButton subscribe;
    // End of variables declaration//GEN-END:variables
}
